defaults: &defaults
  working_directory: ~/vccci
  docker:
    - image: circleci/node:10-browsers


version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - restore_cache:
          keys:
            - repo-{{ .Branch }}-{{ .Revision }}
            - repo-{{ .Branch }}-
            - repo-
      - checkout
      - save_cache:
          key: repo-{{ .Branch }}-{{ .Revision }}
          paths:
            - ".git"
      - restore_cache:
          keys:
          - node_modules-{{ checksum "package-lock.json" }}
          - node_modules-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: node_modules-{{ checksum "package-lock.json" }}
      - run: npm run test:unit
      - run: npm run build
      - persist_to_workspace:
          root: ~/vccci/dist
          paths:
            - ./

  deploy:
    <<: *defaults
    steps:
      - restore_cache:
          keys:
            - repo-{{ .Branch }}-{{ .Revision }}
            - repo-{{ .Branch }}-
            - repo-
      - checkout
      - restore_cache:
          keys:
          - node_modules-{{ checksum "package-lock.json" }}
      - run: npm install
      - attach_workspace:
          at: ~/vccci/dist
      - run: npx firebase deploy --non-interactive --token "$FIREBASE_TOKEN"

workflows:
  version: 2
  build-test-and-approval-deploy:
    jobs:
      - build
      - hold:
          type: approval
          requires:
           - build
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - hold
