defaults: &defaults
  working_directory: ~/vccci
  docker:
    - image: circleci/node:10-browsers


version: 2
jobs:
  prepare:
    <<: *defaults
    steps:
      - checkout
      - run: node --version
      - run: npm --version
      - run: npm install

  build:
    <<: *defaults
    steps:
      - run: npm run build
      - persist_to_workspace:
          root: ~/vccci/dist
          paths:
            - ./

  test:
    <<: *defaults
    steps:
      - run: npm run test:unit

  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/vccci/dist
      - run: npx firebase deploy --non-interactive --token "$FIREBASE_TOKEN"

workflows:
  version: 2
  build-test-and-approval-deploy:
    jobs:
      - prepare
      - build:
          requires:
            - prepare
      - test:
          requires:
            - prepare
      - hold:
          type: approval
          requires:
           - build
           - test
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - hold
